'use strict';

module.exports = {
  apps: [
    {
      name:    'wk-api',
      script:  './apps/api/dist/server.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1800M',
      env_production: {
        NODE_ENV:         'production',
        PORT:             '3001',
        WORKERS_ENABLED:  'false',
      },
      out_file:   './logs/wk-api-out.log',
      error_file: './logs/wk-api-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts:  10,
      min_uptime:    '5s',
    },
    {
      name:    'wk-workers',
      script:  './apps/api/dist/jobs/bootstrap.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1400M',
      env_production: {
        NODE_ENV:        'production',
        WORKERS_ENABLED: 'true',
      },
      out_file:   './logs/wk-workers-out.log',
      error_file: './logs/wk-workers-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 5000,
      max_restarts:  20,
      min_uptime:    '10s',
    },
    {
      name:    'wk-web',
      script:  'node_modules/.bin/next',
      args:    'start',
      cwd:     './apps/web',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '1200M',
      env_production: {
        NODE_ENV: 'production',
        PORT:     '3000',
      },
      out_file:   './logs/wk-web-out.log',
      error_file: './logs/wk-web-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts:  10,
      min_uptime:    '5s',
    },
  ],
};
