export const ERROR_CODES = {
  VALIDATION_BODY:    'VALIDATION_BODY',
  VALIDATION_PARAMS:  'VALIDATION_PARAMS',
  VALIDATION_QUERY:   'VALIDATION_QUERY',

  NOT_FOUND_MATCH:    'NOT_FOUND_MATCH',
  NOT_FOUND_LEAGUE:   'NOT_FOUND_LEAGUE',
  NOT_FOUND_TEAM:     'NOT_FOUND_TEAM',
  NOT_FOUND_PLAYER:   'NOT_FOUND_PLAYER',
  NOT_FOUND_RESOURCE: 'NOT_FOUND_RESOURCE',
  NOT_FOUND_GENERIC:  'NOT_FOUND_GENERIC',

  RATE_LIMIT_CLIENT:  'RATE_LIMIT_CLIENT',

  PROVIDER_AUTH_FAILURE:      'PROVIDER_AUTH_FAILURE',
  PROVIDER_RATE_LIMITED:      'PROVIDER_RATE_LIMITED',
  PROVIDER_UNAVAILABLE:       'PROVIDER_UNAVAILABLE',
  PROVIDER_INVALID_RESPONSE:  'PROVIDER_INVALID_RESPONSE',
  PROVIDER_TIMEOUT:           'PROVIDER_TIMEOUT',

  DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED',
  DATABASE_UNAVAILABLE:  'DATABASE_UNAVAILABLE',

  CONFIG_INVALID:  'CONFIG_INVALID',
  INTERNAL_ERROR:  'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
